# Generated by Django 4.2.7 on 2023-12-01 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_alter_event_id_alter_eventmember_id'),
        ('calendarapp', '0002_auto_20231129_2156'),
    ]

    operations = [
    ]
